# Permalinks
permalink:           pretty

# Setup
title:               Maya's Project Blog
tagline:             Talk Data to Me
url:                 http://mayamadhavan.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Maya Madhavan
  email:             mmadhava100@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mayamadhavan

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'

#Theme
remote_theme: "mmistakes/so-simple-theme"
